### ISSUE TITLE
German Localization for TechSupport & CrashReporter

### ISSUE THREAD

**Issue by J41LBR34KXP** [ashikase/Localization#13]
seems to be impossible to write a pull request...
Anyway, here are the German Translations for TechSupport and
CrashReporter's preferences. I also fixed the App Translation a bit,
and translated the new strings.

Dropbox: https://www.dropbox.com/s/8iiwkcda8h6hosb/de.zip

**Comment by ashikase** [comment]
Thanks; I've manually added and pushed the changes.
